name: Check for Broken Links

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # runs daily at midnight UTC
    - cron: '0 6 * * 1'

jobs:
  lychee-link-check:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: ⚡ Install Lychee
        uses: lycheeverse/lychee-action@v1.9.2

      - name: 🔗 Run Lychee to check links
        run: lychee --verbose --no-progress --exclude-mail --timeout 20 "./**/*.html"
